module demo

enum Direction {
    North
    South
    East
    West
}

struct Vector3D {
    x: float
    y: float
    z: float
}

interface Counter {
    count: int
    msg: string
    increment(step: int)
    decrement(step: int)
    signal reset()
}