module demo

enum Direction {
    North
    South
    East
    West
}

struct Message {
    text: string
}

interface Counter {
    count: int
    increment(step: int)
    decrement(step: int)
    signal reset(count: int)
    say(msg: Message): Message
}