module demo 1.0

enum Direction {
    Up = 1
    Down
    Left
    Right
}

struct Vector3D {
    x: float64
    y: float64
    z: float64
}

interface Counter {
    count: int
    position: Vector3D
    direction: Direction
    increment(step: int)
    decrement()
}